<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.aisen1024</groupId>
    <artifactId>lq-cloud-parent</artifactId>
    <version>1.1.9-high</version>
    <packaging>pom</packaging>
    <description>spring cloud 下一代微服务架构</description>
    <url>https://github.com/aisen1024/lq-cloud</url>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
            <comments>A business-friendly OSS license</comments>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>master</id>
            <email>aisen1024@163.com</email>
            <name>liming.zheng</name>
            <url>https://github.com/aisen1024/lq-cloud</url>
            <roles>
                <role>master</role>
                <role>develop</role>
            </roles>
        </developer>
    </developers>
    <scm>
        <connection>scm:git:git//https://github.com/aisen1024/lq-cloud.git</connection>
        <developerConnection>scm:git:ssh://github.com:aisen1024/lq-cloud.git</developerConnection>
        <url>https://github.com/aisen1024/lq-cloud/tree/develop/src/main</url>
    </scm>


    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serverId>central</serverId>
        <therapi-javadoc.version>0.15.0</therapi-javadoc.version>
    </properties>


    <distributionManagement>
        <snapshotRepository>
            <id>${serverId}</id>
            <url>https://central.sonatype.com/</url>
        </snapshotRepository>
    </distributionManagement>

    <modules>
        <module>framework</module>
        <module>lq-admin</module>
    </modules>

</project>